level_1_data = [
    '                   2 DEF                        ',
    '                  222DEF   N                  1 ',
    '   2           R  ABCDEF2                R      ',
    '   R  KLM      0  GHIDEFX KLM            KSSLLLM',
    ' ABC          N  R   DEFY           KLM         ',
    ' DEF             X   DEFZ       R               ',
    ' GHI      KSLLM  Z   2EF  R   KLM               ',
    '                     2EF  ABC                   ',
    '      KLM            DEF  DEF 2          KLM    ',
    '   2           ABC   GHI  GHI ABBLLLLLL         ',
    ' KLM   N       DEF            DEF             R ',
    '               GHI            DEF           KLM ',
    '      KLM                     DEF               ',
    'R                 ABC         GHI     KLLM      ',
    'KLLM   N          GHI   R        ABC            ',
    '            ABC      ABBC        DEF            ',
    '      KLM   DEF      DEEIBBBC    GHI      LLLLL ',
    '            GHI      DEFEEEEF                   ',
    ' KLM                 DEFHHHHI        KLM        ',
    '     R           KLM DEF     R                  ',
    '     KLM  R          DEF     KLLLM      KLLM    ',
    '          KLM  R     DEF2                     KM',
    '  N            KLM   DEFN                       ',
    ' P    R    N         DEF   R       R            ',
    'ABBBBBBC             DEEBBBBB      X  X  X ABBBC',
    'DEEEEEEF ABBB  ABBBC DEEEEEEE   2  Y  Y  Y DEEEF',
    'GHHHHHHISGHHHSSGHHHISGHHHHHHHSSSLSSZSSZSSZSGHHHI', ]

level_2_data = [
    '                                                ',
    '                                          X1    ',
    '2 N          2    X              2        Y     ',
    'X  X         0   DF              X    X   GHHHI ',
    'GHHI      0   0 0 X              Y    GHM      0',
    '     0         0  Z   X          Z              ',
    '        0  X         GI      AC     2    0     2',
    '  0        Y    N        X  KHI     X   0      0',
    '           Z     2       Z          Y      0  N ',
    '0    AC        ALLM  X     X     0  Y           ',
    '     GI        Y     Y     Y NN 0   DF    KM  0 ',
    '         X     Y     DLLM  DM  0 GHHI           ',
    'KLM      D KLM Z  KLLM    KI KM        X        ',
    '         Z    0 0                      Y       0',
    '     X  0         X                AC  Z    0   ',
    'X   KF            Z   AC      KM   GI           ',
    'GI   DM          0    GI   0                 0  ',
    '     Z     KC               0  AC               ',
    '            Z  0   KM          D2         0     ',
    '  0     X    X                 DC   X      0    ',
    '        Z    Y                 GI   Y AC        ',
    '      X     KHM    KM    KM         Z GI      N ',
    '      Y           O           ALLM             2',
    'R     DM O   X       AC       Y            AC AM',
    'KLM   Y     KF   X   DF 2 2  DM   O        DF2Y ',
    'P     Y      DM  Y   DF 0  0  Y       AC   GHLI ',
    'KLLLLLMSSSOSSSSSSZSSSGISSSSSSSZSSSSSSSGISSSSSSSS']

#   '123456789012345678901234567890123456789012345678"
level_3_data = [
    '                    222                         ',
    '        2     2     333                       1 ',
    '333     3     3     333          2 2   2  2     ',
    '     2          2   333      3   3 3   3  3 3333',
    '     3  2    2  3   333  3   3       2          ',
    '     3 23    3      333  3   3      222         ',
    '     3 33    3  2  3333  3         22222        ',
    '     3  3    3  3  3333 33        2222222       ',
    '     32 3          3333  3                      ',
    '     33 3      2 223333          33333333       ',
    '               3 333333333   3          2       ',
    '               3 333333333             222      ',
    '         2  2  3 333333333                  333 ',
    '         3  3     222          3       333      ',
    '   2  3  3  3     222           333    222222222',
    '  222    3  3     333    3                      ',
    '                                          333   ',
    '  333       222  2   3        3    2            ',
    '  333                  333        222  3        ',
    '  333  333       3                     3       3',
    '    2            222              333  3        ',
    '   222     333                3     2           ',
    '  22222          333               222 2  2  3  ',
    ' P          2  2 2 222                          ',
    '333333333  2 22 2 2   333 333 333   3  3  3   22',
    '333333333  3  3  3    333 333 333      3  3   23',
    '333333333SSSSSSSSSSSSS333S333S333SSSSSS3SS3SSSSS', ]

# level_3 = [
#     '                                                ',
#     ':                   ABC                       1 ',
#     'KLM     0     0     DEF                         ',
#     '                    DEF      X   0 0   0  0 KLLM',
#     '     X          0   DEF  X   Y                  ',
#     '     Y  X    X      DEF  Y   Z                  ',
#     '     Y 0Y    Y     AEEF  Y                      ',
#     '     Y  Y    Z  0  DEEF 0Y                      ',
#     '     Y  Y          DEEF  Z                      ',
#     '     Z0 Z          DEEF          KLLLLLLM       ',
#     '               X ACDEEFABC   0                  ',
#     '               Y DFDEEFDEF                      ',
#     '               Z GIGHHIGHI                  KLM ',
#     '         X  X                 0       KLM       ',
#     '      0  Y  Y                   KLM             ',
#     '         Z  Z     KLM    0                      ',
#     '                                          KLM   ',
#     '  ABC                0        0                 ',
#     '  DEF                  KLM             X       :',
#     '  GHI  KLM       0                     Y       0',
#     '                                  KLM  Z        ',
#     '           KLM                0                 ',
#     '                 KLM                         0  ',
#     ' P                                              ',
#     'ABBBBBBBC             ABC ABC ABC   0  X  X     ',
#     'DEEEEEEEF  0  0  0    DEF DEF DEF      Y  Y     ',
#     'GHHHHHHHISSSSSSSSSSSSSGHISGHISGHISSSSSSZSSZSSSSS', ]


tile_size_convention = 48

screen_width = 1440
screen_height = 810
tile_size = screen_width / tile_size_convention
